In [1]:
import tensorflow as tf


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.19843449, -0.21499678, -0.64833057,  0.25618327,  0.33658338,
         0.10954883,  0.69374245, -0.46648675, -0.08656608,  0.20987913]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.10951027, 0.07242757, 0.04695798, 0.11602052, 0.12573384,
        0.10019644, 0.17970674, 0.05632267, 0.08235323, 0.11077077]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2998 - accuracy: 0.9133

In [9]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0793 - accuracy: 0.9766


[0.07928485423326492, 0.9765999913215637]

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.6391046e-08, 4.6634288e-09, 3.3676148e-05, 4.3909665e-04,
        2.0345342e-11, 2.0635317e-08, 6.5459736e-14, 9.9952197e-01,
        2.6049477e-07, 4.8901757e-06],
       [5.0809401e-08, 9.0553967e-06, 9.9997389e-01, 1.5414007e-05,
        2.5320543e-17, 1.4649347e-06, 4.0829748e-09, 1.3921514e-13,
        2.1700716e-07, 1.7549102e-13],
       [1.3356150e-07, 9.9975306e-01, 6.0424027e-05, 6.4183786e-07,
        3.4203746e-05, 2.0071630e-07, 1.4703526e-05, 8.2471088e-05,
        5.4071366e-05, 1.6878280e-07],
       [9.9993265e-01, 3.0465606e-11, 4.5650111e-05, 2.9392226e-08,
        9.8173158e-09, 7.6522775e-07, 1.6962649e-05, 2.3971731e-07,
        9.8301996e-07, 2.8080303e-06],
       [8.8165399e-07, 1.3482199e-10, 7.7239047e-06, 1.1879013e-07,
        9.9892116e-01, 7.2434472e-07, 9.5456255e-07, 4.3861099e-05,
        1.8982764e-06, 1.0227975e-03]], dtype=float32)>